config/routes.rb
Rails.application.routes.draw do
  

  post 'likes/toggle/:post_id', to: 'likes#toggle', as: :toggle_like

  post 'comments/create', as: :comments
  delete 'comments/:id', to: 'comments#destroy', as: :destroy_comment

	# Post routes
  root 'posts#home'
  post 'posts/create', as: :posts
  delete 'posts/:id', to: 'posts#destroy', as: :destroy_post

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to: user
	belongs_to: post
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy


	# returns true if a user can like this post
	def user_can_like(user_id)
		if self.likes.where(user_id: user_id).length > 0
			return false
		end

		return true

	end


	def like_status_string(user_id)
		if self.user_can_like(user_id)
			return 'Like'
		else
			return 'Unlike'

		end

	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]
  before_action :authorize_user, only: [:destroy]


  def create
    comment = Comment.create(
      content: params[:comment][:content], 
      user_id: current_user.id, 
      post_id: params[:comment][:post_id]
      )

    redirect_to root_path

  end

  def destroy
    @comment.destroy

    redirect_to root_path
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def authorize_user
    if (@comment.user_id != current_user.id)
      redirect_to root_path
    end

  end



end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!


  def toggle

  	# @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])


  	# if @like.blank?
  	# 	@like = Like.create(user_id: current_user.id, post_id: params[:post_id])

  	# else

  	# 	@like.destroy
  	# end
    @post = Post.find(params[:post_id])

    if @post.user_can_like(current_user.id)

      @like = Like.create(user_id: current_user.id, post_id: params[:post_id])

    else
      Like.find_by(user_id: current_user.id, post_id: params[:post_id]).destroy
    end


  	redirect_to root_path


  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_post, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  def home
    # for new posts
  	@post = Post.new

    # for list of posts
  	@posts = Post.all

    # for new comment
    @comment = Comment.new
  end

  def create

  	@post = Post.create(content: params[:post][:content], user_id: current_user.id)
    @comment = Comment.new
  	# redirect_to action: "home"

  end

  def destroy
   @post_id = @post.id
	 @post.destroy

  	# redirect_to action: "home"
  end


  private

  def set_post
  	@post = Post.find(params[:id])
  end

  def authorize_user
  	if (@post.user_id != current_user.id)
  		redirect_to action: "home"
  	end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li>
	<p><%= comment.content %>
		<sub><%= comment.user.email %></sub>
	</p>
	<% if user_signed_in? && comment.user_id ==  current_user.id %>
		<p><%= link_to "Delete", destroy_comment_path(comment.id), method: :delete %></p>
		<% end %>

</li>

app/views/comments/_post_comment.html.erb
<div>
	<h5>Add Comment</h5>
	<% if user_signed_in? %>
	<%= form_for @comment, remote: true do |f| %>
		<%= f.hidden_field :post_id, value: post.id %>

		<%= f.label :content %>
		<%= f.text_area :content %>

		<%= f.submit %>
	<% end %>
	<% end %>

	<ul id="post-comment-list-<%= post.id %>">
		<% post.comments.reverse.each do |c| %>
		<%= render 'comments/comment', comment: c %>
		<% end %>
	</ul>


</div> 

app/views/comments/create.js.erb
console.log('creating comment for a post');

var commentsListContainer = $('#post-comment-list-<%= @new_comment.post_id %>')

var newCommentHTML = $("<%= escape_javascript render 'comments/comment', comment: @new_comment %>");

commentsListContainer.prepend(newCommentHTML);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Connecti</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <div class="common-header">

      <div class='logo'>
        <img width="95" src="http://files.softicons.com/download/social-media-icons/colored-pen-web-icons-by-iconexpo.com/png/256/reddit-pen.png">
      </div>

      <div class='auth-info-links'>
        <% if user_signed_in? %>
        <p><%= current_user.email %></p>
        <p><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>

        <% else %>

          <p><%= link_to "Sign In", new_user_session_path %></p>
          <p><%= link_to "Sign Up", new_user_registration_path %></p>
        <% end %>
      </div>
    </div>


    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
	<div>

		<p><%= post.content %></p>
		<p><%= post.user.email %></p>
		<% if user_signed_in? && post.user_id ==  current_user.id %>
		<p><%= link_to "Delete", destroy_post_path(post.id), method: :delete, remote: true %></p>
		<% end %>

		<% if user_signed_in? %>
		<p>
			<sub>
				<%= post.likes.length %>
				&nbsp
				<%= link_to post.like_status_string(current_user.id), toggle_like_path(post.id), method: :post %>
			</sub>
		</p>
		<% else %>
		<sub>
				<%= post.likes.length %> Likes
		
			</sub>

		<% end %>

		<div>
			<%= render 'comments/post_comment', post: post %>
		</div>
		
	</div>
</li>

app/views/posts/create.js.erb
console.log("new post created");

var newPost = $('<%= escape_javascript render "post" , post: @post %>');
$('#posts-list').prepend(newPost);

app/views/posts/destroy.js.erb
console.log('dstroy post called');
$('#post-<%= @post.id%>').remove();

app/views/posts/home.html.erb
<main id="posts-home">

	<div>Group Links</div>

	<div class="deewar-posts">
		<div class="new-post-form">
			<% if user_signed_in? %>
		<%= form_for @post, remote: true do |f| %>
				<%= f.label :content %>
				<%= f.text_area :content %>

				<%= f.submit %>
			<% end %>
			<% end %>
		</div>

		<div >
			<ul id="posts-list" class="posts-list">
				<% @posts.reverse.each do |p| %>
				<!--  -->
					<%= render 'post', post: p %>

				<% end %>
			</ul>


		</div>
		

	</div>


	<div>Friends</div>

</main>